language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  sonarcloud:
    organization: "lukasz-szewc-github"
branches:
  only:
  - master
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar